version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /movie-rating-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /movie-rating-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /movie-rating-app/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install flask
  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/movie-rating-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/movie-rating-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
